"""
synonyms.py — Compact English synonym map for translation fallback.
When a word is not in the dictionary, try these synonyms.
"""

SYNONYMS = {
    # --- Irregular verb forms (past, participle, gerund) ---
    "went": ["go", "travel", "move", "depart", "leave"],
    "gone": ["go", "travel", "move", "depart", "leave"],
    "going": ["go", "travel", "move", "depart", "leave"],
    "goes": ["go", "travel", "move", "depart", "leave"],
    "ate": ["eat", "consume", "devour", "feed"],
    "eaten": ["eat", "consume", "devour", "feed"],
    "eating": ["eat", "consume", "devour", "feed"],
    "eats": ["eat", "consume", "devour", "feed"],
    "flew": ["fly", "soar", "glide", "float"],
    "flown": ["fly", "soar", "glide", "float"],
    "flying": ["fly", "soar", "glide", "float"],
    "flies": ["fly", "soar", "glide", "float"],
    "ran": ["run", "flee", "rush", "sprint", "hurry"],
    "running": ["run", "flee", "rush", "sprint"],
    "runs": ["run", "flee", "rush", "sprint"],
    "swam": ["swim", "float", "paddle"],
    "swum": ["swim", "float", "paddle"],
    "swimming": ["swim", "float", "paddle"],
    "drove": ["drive", "steer", "ride", "travel"],
    "driven": ["drive", "steer", "ride", "travel"],
    "driving": ["drive", "steer", "ride", "travel"],
    "rode": ["ride", "travel", "mount"],
    "ridden": ["ride", "travel", "mount"],
    "riding": ["ride", "travel", "mount"],
    "sang": ["sing", "chant", "hum"],
    "sung": ["sing", "chant", "hum"],
    "singing": ["sing", "chant", "hum"],
    "drew": ["draw", "sketch", "paint"],
    "drawn": ["draw", "sketch", "paint"],
    "drawing": ["draw", "sketch", "paint"],
    "grew": ["grow", "increase", "develop"],
    "grown": ["grow", "increase", "develop"],
    "growing": ["grow", "increase", "develop"],
    "knew": ["know", "understand", "comprehend"],
    "known": ["know", "understand", "comprehend"],
    "knowing": ["know", "understand", "comprehend"],
    "threw": ["throw", "toss", "cast", "fling"],
    "thrown": ["throw", "toss", "cast", "fling"],
    "throwing": ["throw", "toss", "cast", "fling"],
    "blew": ["blow", "breathe", "puff"],
    "blown": ["blow", "breathe", "puff"],
    "blowing": ["blow", "breathe", "puff"],
    "broke": ["break", "shatter", "crack", "destroy"],
    "broken": ["break", "shatter", "crack", "destroy"],
    "breaking": ["break", "shatter", "crack", "destroy"],
    "chose": ["choose", "select", "pick"],
    "chosen": ["choose", "select", "pick"],
    "choosing": ["choose", "select", "pick"],
    "froze": ["freeze", "chill", "harden"],
    "frozen": ["freeze", "chill", "harden"],
    "freezing": ["freeze", "chill", "harden"],
    "spoke": ["speak", "talk", "say", "utter"],
    "spoken": ["speak", "talk", "say", "utter"],
    "speaking": ["speak", "talk", "say", "utter"],
    "woke": ["wake", "awaken", "rouse"],
    "woken": ["wake", "awaken", "rouse"],
    "waking": ["wake", "awaken", "rouse"],
    "wore": ["wear", "dress", "clothe"],
    "worn": ["wear", "dress", "clothe"],
    "wearing": ["wear", "dress", "clothe"],
    "wrote": ["write", "record", "inscribe", "compose"],
    "written": ["write", "record", "inscribe", "compose"],
    "writing": ["write", "record", "inscribe", "compose"],
    "read": ["read", "study", "scan"],
    "reading": ["read", "study", "scan"],
    "saw": ["see", "look", "watch", "observe", "notice"],
    "seen": ["see", "look", "watch", "observe", "notice"],
    "seeing": ["see", "look", "watch", "observe", "notice"],
    "said": ["say", "speak", "talk", "utter"],
    "saying": ["say", "speak", "talk", "utter"],
    "told": ["tell", "say", "inform", "explain"],
    "telling": ["tell", "say", "inform", "explain"],
    "gave": ["give", "offer", "provide", "grant"],
    "given": ["give", "offer", "provide", "grant"],
    "giving": ["give", "offer", "provide", "grant"],
    "took": ["take", "grab", "seize", "carry"],
    "taken": ["take", "grab", "seize", "carry"],
    "taking": ["take", "grab", "seize", "carry"],
    "made": ["make", "create", "build", "produce"],
    "making": ["make", "create", "build", "produce"],
    "found": ["find", "discover", "locate"],
    "finding": ["find", "discover", "locate"],
    "brought": ["bring", "carry", "fetch", "deliver"],
    "bringing": ["bring", "carry", "fetch", "deliver"],
    "heard": ["hear", "listen", "perceive"],
    "hearing": ["hear", "listen", "perceive"],
    "felt": ["feel", "sense", "touch"],
    "feeling": ["feel", "sense", "touch"],
    "thought": ["think", "believe", "consider"],
    "thinking": ["think", "believe", "consider"],
    "came": ["come", "arrive", "approach"],
    "coming": ["come", "arrive", "approach"],
    "became": ["become", "turn", "grow"],
    "becoming": ["become", "turn", "grow"],
    "began": ["begin", "start", "commence"],
    "begun": ["begin", "start", "commence"],
    "beginning": ["begin", "start", "commence"],
    "stood": ["stand", "rise", "remain"],
    "standing": ["stand", "rise", "remain"],
    "sat": ["sit", "rest", "settle"],
    "sitting": ["sit", "rest", "settle"],
    "lay": ["lie", "rest", "recline"],
    "lain": ["lie", "rest", "recline"],
    "lying": ["lie", "rest", "recline"],
    "fell": ["fall", "drop", "descend"],
    "fallen": ["fall", "drop", "descend"],
    "falling": ["fall", "drop", "descend"],
    "lost": ["lose", "misplace", "fail"],
    "losing": ["lose", "misplace", "fail"],
    "paid": ["pay", "compensate", "reward"],
    "paying": ["pay", "compensate", "reward"],
    "met": ["meet", "encounter", "join"],
    "meeting": ["meet", "encounter", "join"],
    "led": ["lead", "guide", "direct"],
    "leading": ["lead", "guide", "direct"],
    "meant": ["mean", "intend", "signify"],
    "meaning": ["mean", "intend", "signify"],
    "kept": ["keep", "hold", "retain"],
    "keeping": ["keep", "hold", "retain"],
    "left": ["leave", "depart", "exit"],
    "leaving": ["leave", "depart", "exit"],
    "let": ["let", "allow", "permit"],
    "letting": ["let", "allow", "permit"],
    "put": ["put", "place", "set", "lay"],
    "putting": ["put", "place", "set", "lay"],
    "set": ["set", "place", "put", "lay"],
    "setting": ["set", "place", "put", "lay"],
    "cut": ["cut", "slice", "chop"],
    "cutting": ["cut", "slice", "chop"],
    "hit": ["hit", "strike", "beat", "knock"],
    "hitting": ["hit", "strike", "beat", "knock"],
    "hurt": ["hurt", "harm", "injure"],
    "hurting": ["hurt", "harm", "injure"],
    "cost": ["cost", "price", "expense"],
    "costing": ["cost", "price", "expense"],
    "spread": ["spread", "scatter", "extend"],
    "spreading": ["spread", "scatter", "extend"],
    "rose": ["rise", "ascend", "climb"],
    "risen": ["rise", "ascend", "climb"],
    "rising": ["rise", "ascend", "climb"],
    "shook": ["shake", "tremble", "quiver"],
    "shaken": ["shake", "tremble", "quiver"],
    "stole": ["steal", "take", "rob"],
    "stolen": ["steal", "take", "rob"],
    "stealing": ["steal", "take", "rob"],
    "forgot": ["forget", "ignore", "overlook"],
    "forgotten": ["forget", "ignore", "overlook"],
    "forgave": ["forgive", "pardon", "excuse"],
    "forgiven": ["forgive", "pardon", "excuse"],
    "hid": ["hide", "conceal", "cover"],
    "hidden": ["hide", "conceal", "cover"],
    "hiding": ["hide", "conceal", "cover"],
    "bit": ["bite", "chew", "gnaw"],
    "bitten": ["bite", "chew", "gnaw"],
    "shone": ["shine", "glow", "radiate"],
    "shining": ["shine", "glow", "radiate"],
    "sank": ["sink", "submerge", "plunge"],
    "sunk": ["sink", "submerge", "plunge"],
    "swung": ["swing", "sway", "rock"],
    "swinging": ["swing", "sway", "rock"],
    "stuck": ["stick", "attach", "fasten"],
    "sticking": ["stick", "attach", "fasten"],
    "spun": ["spin", "rotate", "twirl"],
    "spinning": ["spin", "rotate", "twirl"],
    "crept": ["creep", "crawl", "sneak"],
    "creeping": ["creep", "crawl", "sneak"],
    "slept": ["sleep", "rest", "slumber"],
    "sleeping": ["sleep", "rest", "slumber"],
    "swept": ["sweep", "clean", "brush"],
    "sweeping": ["sweep", "clean", "brush"],
    "wept": ["weep", "cry", "sob"],
    "weeping": ["weep", "cry", "sob"],
    "fed": ["feed", "nourish", "sustain"],
    "feeding": ["feed", "nourish", "sustain"],
    "fled": ["flee", "run", "escape"],
    "fleeing": ["flee", "run", "escape"],
    "hung": ["hang", "suspend", "dangle"],
    "hanging": ["hang", "suspend", "dangle"],
    "taught": ["teach", "instruct", "educate"],
    "teaching": ["teach", "instruct", "educate"],
    "sold": ["sell", "trade", "exchange"],
    "selling": ["sell", "trade", "exchange"],
    "bought": ["buy", "purchase", "acquire"],
    "buying": ["buy", "purchase", "acquire"],
    "caught": ["catch", "grab", "seize", "capture"],
    "catching": ["catch", "grab", "seize", "capture"],
    "fought": ["fight", "battle", "struggle"],
    "fighting": ["fight", "battle", "struggle"],
    "sought": ["seek", "search", "hunt"],
    "seeking": ["seek", "search", "hunt"],
    "built": ["build", "construct", "create"],
    "building": ["build", "construct", "create"],
    "lent": ["lend", "loan", "give"],
    "lending": ["lend", "loan", "give"],
    "spent": ["spend", "use", "consume"],
    "spending": ["spend", "use", "consume"],
    "sent": ["send", "dispatch", "deliver"],
    "sending": ["send", "dispatch", "deliver"],
    "dealt": ["deal", "handle", "manage"],
    "dealing": ["deal", "handle", "manage"],
    "won": ["win", "gain", "achieve"],
    "winning": ["win", "gain", "achieve"],
    "held": ["hold", "grasp", "grip"],
    "holding": ["hold", "grasp", "grip"],
    "dug": ["dig", "excavate"],
    "digging": ["dig", "excavate"],
    "bound": ["bind", "tie", "fasten"],
    "binding": ["bind", "tie", "fasten"],
    "bent": ["bend", "curve", "bow"],
    "bending": ["bend", "curve", "bow"],
    "lit": ["light", "shine", "illuminate"],
    "lighted": ["light", "shine", "illuminate"],
    "slid": ["slide", "slip", "glide"],
    "sliding": ["slide", "slip", "glide"],
    "shut": ["shut", "close", "seal"],
    "shutting": ["shut", "close", "seal"],
    "split": ["split", "divide", "separate"],
    "splitting": ["split", "divide", "separate"],
    "quit": ["quit", "stop", "cease"],
    "quitting": ["quit", "stop", "cease"],
    "bet": ["bet", "wager", "gamble"],
    "betting": ["bet", "wager", "gamble"],
    "cast": ["cast", "throw", "toss"],
    "casting": ["cast", "throw", "toss"],
    "burst": ["burst", "explode", "break"],
    "bursting": ["burst", "explode", "break"],
    "understood": ["understand", "comprehend", "grasp"],
    "understanding": ["understand", "comprehend", "grasp"],
    "mistook": ["mistake", "misunderstand", "confuse"],
    "mistaken": ["mistake", "misunderstand", "confuse"],
    "proved": ["prove", "demonstrate", "show"],
    "proven": ["prove", "demonstrate", "show"],
    "proving": ["prove", "demonstrate", "show"],
    "provided": ["provide", "supply", "give"],
    "providing": ["provide", "supply", "give"],
    "required": ["require", "need", "demand"],
    "requiring": ["require", "need", "demand"],
    "supposed": ["suppose", "assume", "think"],
    "supposing": ["suppose", "assume", "think"],
    "used": ["use", "employ", "utilize"],
    "using": ["use", "employ", "utilize"],
    "tried": ["try", "attempt", "seek"],
    "trying": ["try", "attempt", "seek"],
    "wanted": ["want", "need", "desire"],
    "wanting": ["want", "need", "desire"],
    "needed": ["need", "require", "want"],
    "needing": ["need", "require", "want"],
    "called": ["call", "shout", "summon"],
    "calling": ["call", "shout", "summon"],
    "asked": ["ask", "question", "inquire"],
    "asking": ["ask", "question", "inquire"],
    "answered": ["answer", "reply", "respond"],
    "answering": ["answer", "reply", "respond"],
    "worked": ["work", "labor", "toil"],
    "working": ["work", "labor", "toil"],
    "lived": ["live", "dwell", "reside"],
    "living": ["live", "dwell", "reside"],
    "died": ["die", "perish", "pass"],
    "dying": ["die", "perish", "pass"],
    "killed": ["kill", "slay", "destroy"],
    "killing": ["kill", "slay", "destroy"],
    "loved": ["love", "adore", "cherish"],
    "loving": ["love", "adore", "cherish"],
    "hated": ["hate", "despise", "loathe"],
    "hating": ["hate", "despise", "loathe"],
    "helped": ["help", "aid", "assist"],
    "helping": ["help", "aid", "assist"],
    "hoped": ["hope", "wish", "desire"],
    "hoping": ["hope", "wish", "desire"],
    "feared": ["fear", "dread", "worry"],
    "fearing": ["fear", "dread", "worry"],
    "cried": ["cry", "weep", "sob"],
    "crying": ["cry", "weep", "sob"],
    "laughed": ["laugh", "smile", "chuckle"],
    "laughing": ["laugh", "smile", "chuckle"],
    "smiled": ["smile", "grin", "beam"],
    "smiling": ["smile", "grin", "beam"],
    "shouted": ["shout", "yell", "scream"],
    "shouting": ["shout", "yell", "scream"],
    "whispered": ["whisper", "murmur", "mutter"],
    "whispering": ["whisper", "murmur", "mutter"],
    "promised": ["promise", "swear", "vow"],
    "promising": ["promise", "swear", "vow"],
    "agreed": ["agree", "consent", "accept"],
    "agreeing": ["agree", "consent", "accept"],
    "refused": ["refuse", "deny", "reject"],
    "refusing": ["refuse", "deny", "reject"],
    "allowed": ["allow", "permit", "let"],
    "allowing": ["allow", "permit", "let"],
    "forbade": ["forbid", "prohibit", "ban"],
    "forbidden": ["forbid", "prohibit", "ban"],
    "ordered": ["order", "command", "direct"],
    "ordering": ["order", "command", "direct"],
    "begged": ["beg", "plead", "implore"],
    "begging": ["beg", "plead", "implore"],
    "warned": ["warn", "caution", "alert"],
    "warning": ["warn", "caution", "alert"],
    "advised": ["advise", "counsel", "guide"],
    "advising": ["advise", "counsel", "guide"],
    "suggested": ["suggest", "propose", "recommend"],
    "suggesting": ["suggest", "propose", "recommend"],
    "explained": ["explain", "describe", "clarify"],
    "explaining": ["explain", "describe", "clarify"],
    "described": ["describe", "explain", "detail"],
    "describing": ["describe", "explain", "detail"],
    "counted": ["count", "number"],
    "counting": ["count", "number"],
    "measured": ["measure", "gauge", "estimate"],
    "measuring": ["measure", "gauge", "estimate"],
    "mixed": ["mix", "blend", "combine"],
    "mixing": ["mix", "blend", "combine"],
    "cooked": ["cook", "prepare", "bake"],
    "cooking": ["cook", "prepare", "bake"],
    "baked": ["bake", "cook", "roast"],
    "baking": ["bake", "cook", "roast"],
    "boiled": ["boil", "cook", "heat"],
    "boiling": ["boil", "cook", "heat"],
    "fried": ["fry", "cook", "roast"],
    "frying": ["fry", "cook", "roast"],
    "washed": ["wash", "clean", "rinse"],
    "washing": ["wash", "clean", "rinse"],
    "cleaned": ["clean", "wash", "sweep"],
    "cleaning": ["clean", "wash", "sweep"],
    "dried": ["dry", "wipe"],
    "drying": ["dry", "wipe"],
    "burned": ["burn", "fire", "scorch"],
    "burnt": ["burn", "fire", "scorch"],
    "burning": ["burn", "fire", "scorch"],
    "melted": ["melt", "thaw", "dissolve"],
    "melting": ["melt", "thaw", "dissolve"],
    "flowed": ["flow", "run", "stream"],
    "flowing": ["flow", "run", "stream"],
    "poured": ["pour", "flow", "spill"],
    "pouring": ["pour", "flow", "spill"],
    "filled": ["fill", "pack", "load"],
    "filling": ["fill", "pack", "load"],
    "emptied": ["empty", "clear", "drain"],
    "emptying": ["empty", "clear", "drain"],
    "tied": ["tie", "bind", "fasten"],
    "tying": ["tie", "bind", "fasten"],
    "loosed": ["loose", "free", "release"],
    "loosing": ["loose", "free", "release"],
    "freed": ["free", "release", "liberate"],
    "freeing": ["free", "release", "liberate"],
    "hunted": ["hunt", "chase", "pursue"],
    "hunting": ["hunt", "chase", "pursue"],
    "planted": ["plant", "sow", "seed"],
    "planting": ["plant", "sow", "seed"],
    "harvested": ["harvest", "gather", "collect"],
    "harvesting": ["harvest", "gather", "collect"],
    "buried": ["bury", "hide", "cover"],
    "burying": ["bury", "hide", "cover"],
    "covered": ["cover", "hide", "protect"],
    "covering": ["cover", "hide", "protect"],
    "wrapped": ["wrap", "cover", "bind"],
    "wrapping": ["wrap", "cover", "bind"],
    "folded": ["fold", "bend", "crease"],
    "folding": ["fold", "bend", "crease"],
    "stretched": ["stretch", "extend", "reach"],
    "stretching": ["stretch", "extend", "reach"],
    "reached": ["reach", "extend", "touch"],
    "reaching": ["reach", "extend", "touch"],
    "touched": ["touch", "feel", "contact"],
    "touching": ["touch", "feel", "contact"],
    "pressed": ["press", "push", "squeeze"],
    "pressing": ["press", "push", "squeeze"],
    "crushed": ["crush", "smash", "break"],
    "crushing": ["crush", "smash", "break"],
    "trembled": ["tremble", "shake", "quiver"],
    "trembling": ["tremble", "shake", "quiver"],
    "glowed": ["glow", "shine", "radiate"],
    "glowing": ["glow", "shine", "radiate"],
    "darkened": ["dark", "dim", "shadow"],
    "darkening": ["dark", "dim", "shadow"],
    "brightened": ["bright", "light", "shine"],
    "brightening": ["bright", "light", "shine"],
    "cleared": ["clear", "bright", "clean"],
    "clearing": ["clear", "bright", "clean"],
    "rained": ["rain", "water", "pour"],
    "raining": ["rain", "water", "pour"],
    "snowed": ["snow", "ice", "fall"],
    "snowing": ["snow", "ice", "fall"],
    "thundered": ["thunder", "boom", "roar"],
    "thundering": ["thunder", "boom", "roar"],

    # --- Common verb synonyms ---
    "run": ["flee", "rush", "sprint", "hurry"],
    "walk": ["stroll", "march", "step", "wander"],
    "eat": ["consume", "devour", "feed"],
    "drink": ["sip", "swallow", "gulp"],
    "sleep": ["rest", "slumber", "doze"],
    "work": ["labor", "toil", "serve"],
    "speak": ["talk", "say", "utter"],
    "think": ["believe", "consider", "ponder"],
    "know": ["understand", "comprehend"],
    "see": ["look", "watch", "observe", "notice"],
    "hear": ["listen", "perceive"],
    "feel": ["sense", "touch", "experience"],
    "make": ["create", "build", "construct", "produce"],
    "give": ["offer", "provide", "grant"],
    "take": ["grab", "seize", "catch", "carry"],
    "bring": ["carry", "fetch", "deliver"],
    "show": ["display", "reveal", "demonstrate"],
    "tell": ["say", "inform", "notify"],
    "ask": ["question", "inquire", "request"],
    "answer": ["reply", "respond"],
    "call": ["shout", "summon", "name"],
    "come": ["arrive", "approach", "appear"],
    "go": ["leave", "depart", "travel", "move"],
    "live": ["dwell", "reside", "inhabit"],
    "die": ["perish", "pass"],
    "kill": ["slay", "destroy"],
    "fight": ["battle", "struggle", "combat"],
    "help": ["aid", "assist", "support"],
    "love": ["like", "adore", "cherish"],
    "hate": ["dislike", "despise"],
    "want": ["need", "desire", "wish"],
    "try": ["attempt", "seek"],
    "use": ["employ", "utilize"],
    "find": ["discover", "locate"],
    "lose": ["misplace", "fail"],
    "keep": ["hold", "retain", "maintain"],
    "hold": ["grasp", "grip", "carry"],
    "put": ["place", "set", "lay"],
    "move": ["shift", "transfer", "change"],
    "start": ["begin", "commence"],
    "stop": ["end", "finish", "halt"],
    "open": ["uncover", "reveal"],
    "close": ["shut", "end"],
    "break": ["shatter", "crack", "destroy"],
    "cut": ["slice", "chop"],
    "hit": ["strike", "beat", "knock"],
    "push": ["shove", "press"],
    "pull": ["drag", "draw", "tug"],
    "throw": ["toss", "cast", "fling"],
    "catch": ["grab", "seize", "capture"],
    "send": ["dispatch", "deliver"],
    "receive": ["get", "accept"],
    "buy": ["purchase", "acquire"],
    "sell": ["trade", "exchange"],
    "pay": ["compensate", "reward"],
    "teach": ["instruct", "educate"],
    "learn": ["study", "discover"],
    "read": ["study", "scan"],
    "write": ["record", "inscribe"],
    "draw": ["sketch", "paint"],
    "sing": ["chant"],
    "dance": ["move"],
    "play": ["game", "sport"],
    "grow": ["increase", "develop"],
    "change": ["alter", "modify"],
    "fall": ["drop", "descend"],
    "rise": ["ascend", "climb"],
    "stand": ["rise", "remain"],
    "sit": ["rest"],
    "wait": ["stay", "remain"],
    "follow": ["pursue", "chase"],
    "lead": ["guide", "direct"],
    "carry": ["bear", "transport"],
    "build": ["construct", "create"],
    "destroy": ["ruin", "demolish"],
    "protect": ["guard", "defend"],
    "save": ["rescue", "preserve"],
    "share": ["divide", "distribute"],
    "gather": ["collect", "assemble"],
    "meet": ["encounter", "join"],
    "choose": ["select", "pick"],
    "decide": ["choose", "determine"],
    "remember": ["recall"],
    "forget": ["ignore", "overlook"],
    "hope": ["wish", "desire"],
    "fear": ["dread", "worry"],
    "cry": ["weep", "sob"],
    "laugh": ["smile", "chuckle"],
    "shout": ["yell", "scream"],
    "promise": ["swear", "vow"],
    "allow": ["permit", "let"],
    "forbid": ["prohibit", "ban"],
    "order": ["command", "direct"],
    "advise": ["counsel", "guide"],
    "explain": ["describe", "clarify"],

    # --- Adjective synonyms ---
    "big": ["large", "great", "huge"],
    "small": ["little", "tiny", "minor"],
    "good": ["fine", "nice"],
    "bad": ["evil", "wrong"],
    "beautiful": ["pretty", "lovely"],
    "ugly": ["hideous"],
    "happy": ["glad", "joyful"],
    "sad": ["unhappy", "sorrowful"],
    "strong": ["powerful", "mighty"],
    "weak": ["feeble", "frail"],
    "fast": ["quick", "swift"],
    "slow": ["sluggish"],
    "hot": ["warm"],
    "cold": ["cool", "freezing"],
    "hard": ["tough", "solid"],
    "soft": ["gentle", "tender"],
    "easy": ["simple"],
    "difficult": ["hard", "tough"],
    "new": ["fresh"],
    "old": ["ancient", "aged"],
    "young": ["youthful"],
    "tall": ["high"],
    "short": ["small", "brief"],
    "long": ["extended"],
    "wide": ["broad"],
    "narrow": ["tight", "thin"],
    "thick": ["fat", "dense"],
    "thin": ["slim"],
    "heavy": ["weighty"],
    "light": ["bright"],
    "dark": ["dim", "black"],
    "bright": ["light", "vivid"],
    "clear": ["obvious", "clean"],
    "clean": ["pure"],
    "dirty": ["filthy"],
    "true": ["real", "correct"],
    "false": ["wrong", "fake"],
    "right": ["correct", "proper"],
    "wrong": ["bad", "false"],
    "same": ["identical", "equal"],
    "different": ["various", "distinct"],
    "important": ["significant"],
    "possible": ["feasible"],
    "impossible": ["unfeasible"],
    "necessary": ["needed"],
    "certain": ["sure"],
    "sure": ["certain"],
    "ready": ["prepared"],
    "able": ["capable"],
    "rich": ["wealthy"],
    "poor": ["needy"],
    "free": ["liberated"],
    "safe": ["secure"],
    "dangerous": ["risky"],
    "brave": ["courageous"],
    "wise": ["smart", "intelligent"],
    "foolish": ["stupid", "silly"],
    "kind": ["good", "gentle"],
    "cruel": ["harsh", "mean"],
    "gentle": ["soft", "mild"],
    "rough": ["harsh"],
    "smooth": ["even"],
    "sharp": ["keen"],
    "dull": ["blunt"],
    "sweet": ["sugary"],
    "bitter": ["sour"],
    "fresh": ["new", "cool"],
    "dry": ["arid"],
    "wet": ["moist"],
    "full": ["complete"],
    "empty": ["void"],
    "whole": ["entire"],
    "many": ["numerous", "several"],
    "few": ["several"],
    "much": ["many", "great"],
    "little": ["small"],
    "more": ["additional"],
    "most": ["greatest"],
    "less": ["fewer"],
    "least": ["smallest"],
    "enough": ["sufficient"],
    "very": ["extremely"],
    "quite": ["rather"],
    "almost": ["nearly"],
    "only": ["just", "sole"],
    "just": ["fair"],
    "even": ["flat", "equal"],
    "odd": ["strange"],
    "strange": ["odd"],
    "normal": ["usual"],
    "usual": ["normal"],
    "common": ["ordinary"],
    "rare": ["uncommon"],
    "special": ["particular", "unique"],
    "general": ["common"],
    "specific": ["particular"],
    "public": ["open"],
    "private": ["personal"],
    "secret": ["hidden"],
    "open": ["public"],
    "alive": ["living"],
    "dead": ["deceased"],
    "real": ["actual"],
    "fake": ["false"],
    "natural": ["normal"],
    "wild": ["untamed"],
    "foreign": ["external"],
    "internal": ["inner"],
    "external": ["outer"],
    "upper": ["higher"],
    "lower": ["under"],
    "front": ["forward"],
    "back": ["rear"],
    "center": ["middle"],
    "middle": ["center"],
    "side": ["edge"],
    "edge": ["border"],
    "end": ["finish"],
    "beginning": ["start"],
    "start": ["beginning"],
    "finish": ["end"],
    "final": ["last"],
    "last": ["final"],
    "first": ["initial"],
    "next": ["following"],
    "previous": ["former"],
    "present": ["current"],
    "current": ["present"],
    "past": ["former"],
    "future": ["ahead"],
    "early": ["soon"],
    "late": ["delayed"],
    "soon": ["early"],
    "now": ["present"],
    "always": ["forever"],
    "never": ["not ever"],
    "often": ["frequently"],
    "sometimes": ["occasionally"],
    "quickly": ["fast"],
    "slowly": ["gradually"],
    "carefully": ["cautiously"],
    "loudly": ["noisily"],
    "quietly": ["silently"],
    "softly": ["gently"],
    "gently": ["softly"],
    "clearly": ["obviously"],
    "probably": ["likely"],
    "perhaps": ["maybe"],
    "maybe": ["perhaps"],
    "certainly": ["surely"],
    "actually": ["really"],
    "really": ["truly"],
    "simply": ["just"],
    "especially": ["particularly"],
    "mainly": ["mostly"],
    "generally": ["usually"],
    "completely": ["fully"],
    "totally": ["completely"],
    "exactly": ["precisely"],
    "approximately": ["about"],
    "roughly": ["approximately"],
    "obviously": ["clearly"],
    "apparently": ["seemingly"],
    "however": ["but"],
    "although": ["though"],
    "therefore": ["thus"],
    "nevertheless": ["however"],
    "otherwise": ["else"],
    "instead": ["rather"],
    "yet": ["still"],
    "still": ["yet"],
    "already": ["by now"],
    "also": ["too"],
    "too": ["also"],

    # --- Noun synonyms ---
    "man": ["male", "person"],
    "woman": ["female", "person"],
    "child": ["kid", "young"],
    "baby": ["infant"],
    "boy": ["lad"],
    "girl": ["lass"],
    "father": ["dad", "parent"],
    "mother": ["mom", "parent"],
    "brother": ["sibling"],
    "sister": ["sibling"],
    "husband": ["spouse"],
    "wife": ["spouse"],
    "family": ["kin"],
    "friend": ["companion"],
    "enemy": ["foe"],
    "king": ["ruler"],
    "queen": ["ruler"],
    "chief": ["leader"],
    "leader": ["chief"],
    "warrior": ["fighter"],
    "soldier": ["warrior"],
    "teacher": ["instructor"],
    "student": ["learner"],
    "doctor": ["healer"],
    "healer": ["doctor"],
    "market": ["marketplace", "bazaar", "fair"],
    "merchant": ["trader"],
    "thief": ["robber"],
    "house": ["home"],
    "building": ["structure"],
    "room": ["chamber"],
    "door": ["entrance"],
    "path": ["way"],
    "road": ["path"],
    "street": ["road"],
    "bridge": ["crossing"],
    "tower": ["high building"],
    "castle": ["fortress"],
    "village": ["town"],
    "town": ["city"],
    "city": ["town"],
    "country": ["land"],
    "world": ["earth"],
    "place": ["location"],
    "area": ["region"],
    "mountain": ["hill"],
    "hill": ["mountain"],
    "valley": ["dale"],
    "river": ["stream"],
    "lake": ["pond"],
    "sea": ["ocean"],
    "forest": ["woods"],
    "tree": ["wood"],
    "flower": ["bloom"],
    "grass": ["herb"],
    "stone": ["rock"],
    "fire": ["flame"],
    "water": ["fluid"],
    "wind": ["breeze"],
    "rain": ["shower"],
    "storm": ["tempest"],
    "snow": ["ice"],
    "sun": ["sunlight"],
    "moon": ["lunar"],
    "star": ["stellar"],
    "sky": ["heavens"],
    "earth": ["ground"],
    "animal": ["beast"],
    "bird": ["fowl"],
    "fish": ["sea creature"],
    "dog": ["hound"],
    "horse": ["steed"],
    "cow": ["cattle"],
    "pig": ["hog"],
    "sheep": ["lamb"],
    "chicken": ["hen"],
    "snake": ["serpent"],
    "wolf": ["wolf"],
    "bear": ["bear"],
    "rabbit": ["hare"],
    "mouse": ["rat"],
    "insect": ["bug"],
    "tree": ["wood"],
    "fruit": ["produce"],
    "seed": ["grain"],
    "leaf": ["foliage"],
    "branch": ["limb"],
    "root": ["base"],
    "gold": ["metal"],
    "silver": ["metal"],
    "iron": ["metal"],
    "time": ["period"],
    "day": ["daylight"],
    "night": ["darkness"],
    "morning": ["dawn"],
    "evening": ["dusk"],
    "year": ["year"],
    "story": ["tale"],
    "word": ["term"],
    "name": ["title"],
    "book": ["volume"],
    "writing": ["text"],
    "message": ["note"],
    "speech": ["talk"],
    "language": ["tongue"],
    "voice": ["sound"],
    "music": ["song"],
    "game": ["play"],
    "work": ["labor"],
    "job": ["work"],
    "rest": ["break"],
    "sleep": ["rest"],
    "dream": ["vision"],
    "thought": ["idea"],
    "mind": ["brain"],
    "memory": ["remembrance"],
    "reason": ["cause"],
    "result": ["effect"],
    "purpose": ["goal"],
    "plan": ["scheme"],
    "method": ["way"],
    "tool": ["instrument"],
    "weapon": ["arm"],
    "battle": ["fight"],
    "war": ["conflict"],
    "peace": ["calm"],
    "life": ["living"],
    "death": ["end"],
    "birth": ["beginning"],
    "health": ["wellness"],
    "sickness": ["illness"],
    "pain": ["hurt"],
    "love": ["affection"],
    "joy": ["happiness"],
    "fear": ["dread"],
    "anger": ["rage"],
    "hope": ["wish"],
    "faith": ["belief"],
    "truth": ["fact"],
    "lie": ["falsehood"],
    "power": ["strength"],
    "freedom": ["liberty"],
    "justice": ["fairness"],
    "law": ["rule"],
    "spirit": ["soul"],
    "god": ["deity"],
    "heaven": ["sky"],
    "hell": ["underworld"],
}
